# Generated by Django 5.2.13 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LibrarySource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=120)),
                ("url", models.URLField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("free_elibrary", "Free E-Library"),
                            ("gdrive", "G-Drive"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={"ordering": ["sort_order", "label"]},
        ),
    ]
