# Generated by Django 5.2.13 on 2026-04-14 00:00

from django.db import migrations


DEFAULT_SOURCES = [
    ("Free E-Library", "https://data.adb.org/dataset/green-and-blue-bond-impact-report", "free_elibrary", 0),
]


def seed_sources(apps, schema_editor):
    LibrarySource = apps.get_model("search", "LibrarySource")
    for label, url, category, sort_order in DEFAULT_SOURCES:
        LibrarySource.objects.get_or_create(
            label=label,
            defaults={"url": url, "category": category, "sort_order": sort_order, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_sources, migrations.RunPython.noop),
    ]
