# Generated by Django 5.2.13 on 2026-04-14 00:00

from django.db import migrations


DEFAULT_SOURCES = [
    ("Judiciary E-Library", "https://elibrary.judiciary.gov.ph/", "free_elibrary", 0),
    ("ADB Data Portal", "https://data.adb.org/dataset/green-and-blue-bond-impact-report", "free_elibrary", 1),
    ("OATD (Open Access Theses and Dissertations)", "https://oatd.org/", "free_elibrary", 2),
    ("NDLTD Global ETD Search", "https://ndltd.org/", "free_elibrary", 3),
    ("ERIC Education Resources", "https://eric.ed.gov/", "free_elibrary", 4),
    ("CORE (Open Access Research)", "https://core.ac.uk/", "free_elibrary", 5),
    ("BASE Academic Search", "https://www.base-search.net/", "free_elibrary", 6),
    ("DOAJ Journals", "https://doaj.org/", "free_elibrary", 7),
    ("UNESCO Digital Library", "https://unesdoc.unesco.org/", "free_elibrary", 8),
    ("World Bank Open Knowledge Repository", "https://openknowledge.worldbank.org/", "free_elibrary", 9),
]


def seed_more_sources(apps, schema_editor):
    LibrarySource = apps.get_model("search", "LibrarySource")
    for label, url, category, sort_order in DEFAULT_SOURCES:
        LibrarySource.objects.get_or_create(
            label=label,
            defaults={"url": url, "category": category, "sort_order": sort_order, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_seed_default_sources"),
    ]

    operations = [
        migrations.RunPython(seed_more_sources, migrations.RunPython.noop),
    ]
