# Generated by Django 5.2.13 on 2026-04-10 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('preview_file', models.FileField(upload_to='thesis_previews/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='theses.thesis')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('thesis', 'page_number')},
            },
        ),
    ]
