# Generated by Django 5.2.13 on 2026-04-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0002_thesispreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
