# Generated by Django 5.2.13 on 2026-04-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_alter_thesis_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash of the PDF file for duplicate detection', max_length=64),
        ),
    ]
