# Generated by Django 5.2.13 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theses", "0004_thesis_file_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesis",
            name="source_label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="thesis",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded File"),
                    ("free_elibrary", "Free E-Library"),
                    ("gdrive", "Google Drive"),
                    ("mixed", "Uploaded + External"),
                ],
                db_index=True,
                default="uploaded",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="thesis",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="thesis",
            name="pdf_file",
            field=models.FileField(blank=True, upload_to="theses/%Y/%m/"),
        ),
    ]
