# Generated by Django 5.2.13 on 2026-04-14 00:00

from django.db import migrations, models
from django.db.models import deletion


class Migration(migrations.Migration):

    dependencies = [
        ("theses", "0005_thesis_external_sources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thesis",
            name="abstract",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="thesis",
            name="course",
            field=models.ForeignKey(blank=True, null=True, on_delete=deletion.PROTECT, related_name="theses", to="theses.course"),
        ),
        migrations.AlterField(
            model_name="thesis",
            name="preview_page",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="thesis",
            name="title",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
