# Generated by Django 5.2.13 on 2026-04-14 00:00

from django.db import migrations, models


def backfill_null_course(apps, schema_editor):
    Thesis = apps.get_model("theses", "Thesis")
    Course = apps.get_model("theses", "Course")

    fallback_course = Course.objects.order_by("id").first()
    if fallback_course is None:
        fallback_course = Course.objects.create(name="General", code="", department="")

    Thesis.objects.filter(course__isnull=True).update(course=fallback_course)


class Migration(migrations.Migration):

    dependencies = [
        ("theses", "0006_make_link_only_fields_optional"),
    ]

    operations = [
        migrations.RunPython(backfill_null_course, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="thesis",
            name="source_label",
        ),
        migrations.RemoveField(
            model_name="thesis",
            name="source_type",
        ),
        migrations.RemoveField(
            model_name="thesis",
            name="source_url",
        ),
        migrations.AlterField(
            model_name="thesis",
            name="abstract",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="thesis",
            name="course",
            field=models.ForeignKey(on_delete=models.PROTECT, related_name="theses", to="theses.course"),
        ),
        migrations.AlterField(
            model_name="thesis",
            name="pdf_file",
            field=models.FileField(upload_to="theses/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="thesis",
            name="preview_page",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="thesis",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
